travis:
  secure:
    BINSTAR_TOKEN: KhtVNWUUGlHeAxjLedIOBG2idkrsk87BKIt3nCxGLwm6c8R/iEawSLKXj0hvyMXJpTU0kzih6WipS/eiIxEQb7pwxDTIvGmefEVpYgPR9N6rnmrx6crGRcow8JfPc6UsCkuvOuxhquFg0dgXJ2HMi9MnessaBfwASW87Poho9HPPEk84+urVbihxYHb4tuRSERnBEbmULDr0yoJ2j860xyO2MH14wSZk3ZvbW4IjJiAB9TgcUOGOMcQYHSMboK/rw23L7La37rQMC0BfF8MTnPNdHqglOd1LVYh0Ojef8LWKy+p4eFVjZZmSYRhvwsgAlrcJbIDpy1WqqiaYQ/rgcOhtzYWTTm4HgdNG3fcLWy05Dz4YpghBEdbtwGev1gQzwPrvWDLkDMr+rCfLQWsmeUTcZ8IfKA1ZrVhwJuVk17XxbuiCw+i/2hym5S2l8cF6VqIQl6oBYwp1PTS5+Q4Hb2HUAZluIMqTi5ivncJxKUWbJ4ksP29Gl/qw0XnDwlsuTytqbUyvIQRvcJJEt/46Oao1rRQ9nFHIMfrIGc8avyloUC0eYR2R/3spK6MZOCSqw+ZmPG5ai5UMIFSjIbVAz64IQyWlxJmaUXmrVUwJv+fUcA9LxyL+5mNRfbSRLoXgJCPo05XMknJgZZwdlDbtFfnhYfBnyj/JjvsgVf0VgqA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
